### ISSUE TITLE
Echidna unable to publish Note updates?

### ISSUE THREAD

**Issue by anssiko** [w3c/motion-sensors#28]
@dontcallmedom @xfq, can we use Echidna to publish updates to this Note? We're hitting the following error (using https://github.com/w3c/sensors/blob/master/echidna.sh that works fine for other non-Note specs):

>Documents going from non-REC track to REC-track are not supported yet.
https://lists.w3.org/Archives/Public/public-tr-notifications/2017Aug/0073.html

The same error is reported, regardless of whether in the metadata we declare:

```
Status: ED
```

or 

```
Status: NOTE
```

If this is an Echidna feature, could you meanwhile help us manually publish an updated Note?

**Comment by dontcallmedom** [comment]
@anssiko the key is not the "Status:" bit in the document, but the one in the command line invokation ( --md-status=NOTE).

I tried publishing it myself with that fixed, but there is [another bug with the document](https://lists.w3.org/Archives/Public/public-tr-notifications/2017Aug/0088.html) - it sounds like it doesn't use the proper boilerplate to link it to the DAS WG.

**Comment by alexshalamov** [comment]
@dontcallmedom is "Group: dap" not enough to link it to DAS WG?

**Comment by dontcallmedom** [comment]
@alexshalamov  it probably would if we had the right boilerplate for Notes in bikeshed, but it [looks like we don't](https://github.com/tabatkins/bikeshed/tree/master/bikeshed/boilerplate/dap) - I'm assuming the boilerplate would be needed to tell which group is producing the Note. At the same time, I see that we got the previous note published without that mention, so I'm a bit puzzled.

@xfq any chance you could investigate, maybe with @tripu 's help?

**Comment by tripu** [comment]
It looks like Specberus is not finding the deliverer(s) of this spec.

Specberus [finds the deliverer okay in the latest published version](https://www.w3.org/pubrules/api/metadata?url=https%3A%2F%2Fwww.w3.org%2FTR%2Fmotion-sensors%2F), though.

Can you guys share with me the resulting NOTE (the output of Bikeshed for [the current ED](https://w3c.github.io/motion-sensors/); what goes inside the TAR file submitted to Echidna)? That may help debug the issue.

**Comment by xfq** [comment]
@tripu Here's the resulting NOTE. For Some Reason™ the Status section looks empty... Like @dontcallmedom said, perhaps we do not have the right boilerplate for Working Group Notes in Bikeshed.

(I compressed the tar file with zip, because GitHub doesn't support .tar file upload.)

[test.tar.zip](https://github.com/w3c/motion-sensors/files/1231465/test.tar.zip)

**Comment by tripu** [comment]
Thank you, @xfq. Yes, the SotD section is empty.

These are the patterns Specberus uses to identify the deliverers:
[`w3c/specberus:/lib/validator.js#L340-L343`](https://github.com/w3c/specberus/blob/master/lib/validator.js#L340-L343)

The SotD is okay in [the version published currently](https://www.w3.org/TR/motion-sensors/). Did you guys change anything after that?

**Comment by alexshalamov** [comment]
@tripu If I remember correclty, the only 'boilerplate' related change was https://github.com/w3c/motion-sensors/commit/0d846e0f0d2639115eae74511951ddad6c73d296 Level: 1 => Level: none and https://github.com/w3c/motion-sensors/commit/00eae0281808d0e1e829362fee79076760feeff6 link to previous version.

**Comment by xfq** [comment]
It seems that we don't have a `status-NOTE.include` file in the Bikeshed boilerplate: https://github.com/tabatkins/bikeshed/tree/master/bikeshed/boilerplate/dap

However, the CSS WG doesn't have it either, and it has WG Notes published with Bikeshed: https://www.w3.org/TR/css-2017/

And I don't know how the previous note was published...

**Comment by xfq** [comment]
I saw a `<div boilerplate=status>` element in the CSS WG Note: https://github.com/w3c/csswg-drafts/blob/eee458baa78b4aabd57da71a192ea88e7cff1ecd/css-2017/Overview.bs#L26-L30

I'll try to add a similar one to motion-sensors and generate a tar file to see if it works.

**Comment by xfq** [comment]
It still doesn't work... Strangely, the background-image on the left is https://www.w3.org/StyleSheets/TR/2016/logos/NOTE instead of https://www.w3.org/StyleSheets/TR/2016/logos/WG-Note

I'll investigate further later.

**Comment by xfq** [comment]
Spent a few hours on this issue... Although I haven't found the source of the issue (yet), I just found out that the Status section of the previous Note was added (and patched) manually by @anssiko:

* https://github.com/w3c/motion-sensors/commit/66692e657a78bb8914ff927966b42cf86f29fa2f
* https://github.com/w3c/motion-sensors/commit/f0800ddb80af4b2bfee24fc2e3943edd9b226c44

So this doesn't seem to be a new issue. Maybe I should ask @tabatkins for help...

**Comment by xfq** [comment]
(I'll continue to look for ways to publish this document automatically, instead of patching it manually each time.)

**Comment by xfq** [comment]
Submitted tabatkins/bikeshed#1073 and tabatkins/bikeshed#1074.

**Comment by anssiko** [comment]
@xfq, thanks for your hard work debugging this issue. When you have all the required upstream changes landed to fix the publication issue, feel free to publish an updated Working Draft on our behalf using the latest Editor's Draft at https://w3c.github.io/motion-sensors/ as its basis.

(I had entirely forgotten that I had to manually patch the spec previously in order to publish it.)

**Comment by xfq** [comment]
@anssiko I patched the style sheet manually to pass the publication rules this time.

For automatic publishing, I think we still need to wait tabatkins/bikeshed#1073.

**Comment by anssiko** [comment]
https://github.com/tabatkins/bikeshed/issues/1073 was fixed and closed but https://github.com/w3c/motion-sensors/blob/gh-pages/echidna.sh still reports https://lists.w3.org/Archives/Public/public-tr-notifications/2017Aug/0130.html specifically "You are not participating in the following groups:" and "You are not authorized to publish" errors.

@xfq, thanks for your help.

**Comment by dontcallmedom** [comment]
I have identified [one more change needed in bikeshed](https://github.com/tabatkins/bikeshed/pull/1080). 

note that the `echidna.sh` script will need to use `WG-NOTE` rather than `NOTE`. Also, my last attempt to publish with echidna (with the bikeshed patch in) [failed with messages about the version links](https://lists.w3.org/Archives/Public/public-tr-notifications/2017Aug/0134.html) that I haven't looked into.

**Comment by anssiko** [comment]
@dontcallmedom, thanks! I [updated] `echidna.sh` in this repo accordingly.

[updated]: https://github.com/w3c/motion-sensors/commit/c145f39903d4cbd7ccdc3aa86f0185597944eb34

**Comment by dontcallmedom** [comment]
found the source of the other failure, and filed a [related bikeshed issue](https://github.com/tabatkins/bikeshed/issues/1081)

**Comment by dontcallmedom** [comment]
I've been able to publish an [updated version of the note](https://www.w3.org/TR/2017/NOTE-motion-sensors-20170830/) out of the bikeshed processing as https://github.com/tabatkins/bikeshed/issues/1081 got fixed, but there is one last issue [in bikeshed to be solved](https://github.com/tabatkins/bikeshed/pull/1083) for our script to work as is

**Comment by anssiko** [comment]
Thanks for your efforts. I though this was just something I had overlooked, but it turns out we've now had to fix 4 bikeshed issues (to date), consolidated here, should we run into related problems in the future:

* https://github.com/tabatkins/bikeshed/issues/1073
  * https://github.com/tabatkins/bikeshed/commit/14c4d48c5433c4ae992bbbe5dd02f26d7681dd68
* https://github.com/tabatkins/bikeshed/pull/1074
  * https://github.com/tabatkins/bikeshed/commit/fb5d417f6a948f701a265e662dce85aa0cf4ee03
* https://github.com/tabatkins/bikeshed/issues/1081
  * https://github.com/tabatkins/bikeshed/commit/123a071ec7345e8c5d58a49514b05930289ab030
* https://github.com/tabatkins/bikeshed/pull/1083
  * (pending landing)

**Comment by dontcallmedom** [comment]
https://github.com/tabatkins/bikeshed/pull/1083 got merged, and I have now [successfully run](https://lists.w3.org/Archives/Public/public-tr-notifications/2017Aug/0144.html) `echidna.sh`, so closing this issue

**Comment by anssiko** [comment]
Thanks!
