### ISSUE TITLE
Link to calibration dfn in Generic Sensor API

### ISSUE THREAD

**Issue by tobie** [w3c/motion-sensors#3]
> Most gyroscope sensors applies some soft of drift compensation in hardware for known low frequency caused by adjacent hardware on the device.

That sounds like you're describing calibration. If so, care to link it to it's [generic sensor definition](https://w3c.github.io/sensors/#calibration) (via Bikeshed's `[=calibration=]` syntax)? And fix the latter if you think it needs fixing.

**Comment by kenchris** [comment]
Let me look at this Friday
