### ISSUE TITLE
Consider using MathJax for math

### ISSUE THREAD

**Issue by kenchris** [w3c/motion-sensors#8]
This is used in https://www.w3.org/TR/mediacapture-depth/ already and renders nicely.

This way we could we properly rendered unit vectors etc, instead of approximations like ĝ, ê, uG, uE etc and the integrals:

a = g×sin(θ), x = ½×at2

Will look more correct.

@anssiko ?

**Comment by anssiko** [comment]
I would say, don't add MathJax dependency, if you can live without it. It adds complexity to the spec production toolchain, requires a custom build step etc.
